name: WellTrack_App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t maneesh0801/welltrack:latest .

    # Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push maneesh0801/welltrack:latest

    # Deploy to AWS ECS
    - name: Deploy to Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        cluster: WellTrack
        service: welltrack_service
        task-definition: |
          family: welltrack
          containerDefinitions:
            - name: welltrack-container
              image: your-dockerhub-username/welltrack:latest
              memory: 512
              cpu: 256
              essential: true
              portMappings:
                - containerPort: 8000
                  hostPort: 8000
